name: CI to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy
        env: 
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > sshkey
          chmod 600 sshkey

          ssh -o "StrictHostKeyChecking=no" -i sshkey $USER_NAME@$HOSTNAME '
            cd browser-game &&
            git stash &&
            git checkout main &&
            git pull &&
            pm2 restart all
          '
